######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 27 21:34:14 2007
######################################################################

TEMPLATE = app
TARGET = adage
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += game.h gameui.h math/const.h math/point.h math/real.h math/segment.h math/vector.h world/wall.h world/map.h ui/blueprint.h
SOURCES += gameui.cpp main.cpp ui/blueprint.cpp
